# version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend/:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    networks:
      - app-network

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=mydatabase
    
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - /home/ael/Desktop/backend-go/Database:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "8081:8080"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
